version: "3.6"
services:
  app:
    container_name: Kickoff
    hostname: Kickoff
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
    ports:
      - 8080:8080